# Generated by Django 5.2.4 on 2025-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderfile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
    ]
