# Generated by Django 5.2.4 on 2025-07-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_installment_count_order_is_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
