# Generated by Django 5.2.4 on 2025-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('order', '0004_alter_order_installment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='files',
            field=models.ManyToManyField(blank=True, to='file.file'),
        ),
        migrations.DeleteModel(
            name='OrderFile',
        ),
    ]
