# Generated by Django 5.2.4 on 2025-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_files_delete_orderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='order', max_length=10),
        ),
    ]
