# Generated by Django 5.2.4 on 2025-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='get_or_take',
            field=models.CharField(choices=[('get_order', 'Get_order'), ('give_order', 'Give_order')], default=' get_order', max_length=20),
        ),
    ]
