# Generated by Django 5.2.4 on 2025-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('order', '0008_alter_order_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='files',
            field=models.ManyToManyField(blank=True, to='file.file'),
        ),
    ]
