# Generated by Django 5.2.4 on 2025-07-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='get_or_take',
            new_name='get_or_give',
        ),
    ]
