# Generated by Django 5.2.4 on 2025-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='get_order',
            field=models.BooleanField(default=False),
        ),
    ]
