# Generated by Django 5.2.4 on 2025-07-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_get_order'),
        ('installmentpayment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpayment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installmentpayment', to='customer.customer'),
            preserve_default=False,
        ),
    ]
