# Generated by Django 5.2.4 on 2025-07-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_files_delete_orderfile'),
        ('payment', '0003_installmentpayment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='order.order'),
        ),
    ]
