# Generated by Django 5.2.4 on 2025-07-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='order',
        ),
    ]
