# Generated by Django 5.2.4 on 2025-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_remove_balance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='change',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
