# Generated by Django 5.2.4 on 2025-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_balance_change_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='reason',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment')], max_length=20),
        ),
    ]
